import { Clock,Info,Lightbulb,Link2 } from "lucide-react";
import { formatTrickName } from "@/lib/trickDisplay";
import type { TrainingCategory,WeeklyOffTrainingDay } from "@/lib/types";
import type { SelectedTrickDisplayStance } from "@/lib/trickStance";

const colors:Record<TrainingCategory,string>={"シバカツ":"bg-sky-50 text-sky-600","筋トレ":"bg-orange-50 text-orange-600","柔軟":"bg-emerald-50 text-emerald-600"};
export default function OffTrainingDayCard({entry,today,selectedStance="regular"}:{entry:WeeklyOffTrainingDay;today:boolean;selectedStance?:SelectedTrickDisplayStance}){
  const resting=entry.items.length===0;
  return <article className={`min-w-[280px] snap-center rounded-3xl border p-4 shadow-card sm:min-w-0 ${today?"border-glacier bg-ice/50 ring-2 ring-glacier/10":"border-white/80 bg-white"}`}><div className="flex items-start justify-between"><div><p className={`text-xs font-black ${today?"text-glacier":"text-slate-400"}`}>{entry.day}曜日 {today&&"・今日"}</p><h3 className="mt-1 text-lg font-black">{entry.dayType}</h3>{entry.title!==entry.dayType&&entry.dayType!=="休み"&&<p className="mt-1 text-xs text-slate-400">{entry.title}</p>}</div>{!resting&&<span className="flex items-center gap-1 rounded-full bg-white px-2 py-1 text-[10px] font-bold text-slate-500"><Clock size={12}/>{entry.estimatedMinutes}分</span>}</div>{resting?<div className="mt-5 rounded-2xl bg-slate-50 px-4 py-6 text-center"><p className="text-sm font-bold text-slate-400">休み</p><p className="mt-1 text-[11px] text-slate-400">軽いストレッチだけでもOK</p></div>:<div className="mt-4 space-y-3">{entry.items.map((item)=><div key={`${entry.day}-${item.name}`} className="rounded-2xl bg-white p-3"><div className="flex items-start justify-between gap-2"><div><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${colors[item.category]}`}>{item.category}</span><p className="mt-2 font-black">{item.name}</p></div><p className="max-w-28 text-right text-[11px] font-bold text-glacier">{item.amount}</p></div>{item.menuCategory&&<p className="mt-2 text-[11px] font-bold text-emerald-600">系統：{item.menuCategory}{item.difficulty?` ・ 難易度 Lv.${item.difficulty}`:""}</p>}{item.relatedSnowTrick&&<p className="mt-1 flex gap-1 text-[11px] text-glacier"><Link2 size={11} className="mt-0.5 shrink-0"/>関連雪上技：{formatTrickName(item.relatedSnowTrick, selectedStance)}</p>}<p className="mt-2 text-xs text-slate-500">目的：{item.purpose}</p>{item.tip&&<p className="mt-1 flex gap-1 text-[10px] text-amber-600"><Lightbulb size={11} className="mt-0.5 shrink-0"/>コツ：{item.tip}</p>}<p className="mt-1 flex gap-1 text-[10px] text-slate-400"><Info size={11} className="mt-0.5 shrink-0"/>{item.caution}</p></div>)}</div>}</article>;
}
