import Link from "next/link";
import { ChevronRight, Heart, Lock } from "lucide-react";
import { formatTrickName } from "@/lib/trickDisplay";
import { selectedStanceLabels, trickStanceLabels } from "@/lib/trickStance";
import type { Trick } from "@/lib/types";
import type { SelectedTrickDisplayStance } from "@/lib/trickStance";

export default function TrickCard({ trick, compact=false, showUserData=true, selectedStance="regular", canUse=true }: { trick:Trick; compact?:boolean; showUserData?:boolean; selectedStance?:SelectedTrickDisplayStance; canUse?:boolean }) {
  return <Link href={`/tricks/${trick.id}?stance=${selectedStance}`} className={`card group block ${compact ? "!rounded-2xl !p-3" : ""} ${canUse ? "" : "border-amber-100 bg-amber-50/35"}`}><div className="flex items-center gap-3"><div className={`grid shrink-0 place-items-center rounded-2xl font-black ${canUse?"bg-gradient-to-br from-cyan-100 to-blue-100 text-glacier":"bg-white text-amber-600"} ${compact ? "h-11 w-11 text-xs" : "h-16 w-16"}`}>{canUse?`Lv.${trick.difficulty}`:<Lock size={compact?17:22}/>}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h3 className="truncate font-black">{formatTrickName(trick.nameJa, selectedStance)}</h3>{showUserData&&trick.favorite&&canUse&&<Heart size={15} className="fill-rose-400 text-rose-400"/>}</div><p className="mt-0.5 text-xs text-slate-400">{trick.nameEn}</p><div className="mt-2 flex flex-wrap gap-1.5"><span className="rounded-full bg-ice px-2 py-1 text-[10px] font-bold text-glacier">{trick.category}</span>{!canUse&&<><span className="rounded-full bg-amber-100 px-2 py-1 text-[10px] font-black text-amber-700">有料トリック</span><span className="rounded-full bg-white px-2 py-1 text-[10px] font-bold text-amber-700">Premium登録で利用できます</span></>}<span className="rounded-full bg-slate-50 px-2 py-1 text-[10px] font-bold text-slate-500">対応: {trickStanceLabels[trick.stance ?? "both"]}</span><span className="rounded-full bg-blue-50 px-2 py-1 text-[10px] font-bold text-blue-600">{selectedStanceLabels[selectedStance]}</span>{showUserData&&canUse&&<span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold text-slate-500">{trick.masteryStatus}</span>}</div></div><ChevronRight size={18} className="text-slate-300"/></div></Link>;
}
