"use client";

import { getCurrentUser } from "./auth";
import { initialGoals,initialPracticeLogs,initialProfile,initialTricks } from "./mockData";
import { isSupabaseConfigured,supabase } from "./supabase";
import type { Goal,OffTrainingPlan,OffTrainingPlanItem,OffTrainingPreferences,PracticeLog,Profile,Trick,Weekday,WeeklyOffTrainingDay } from "./types";

const baseKeys={tricks:"gratri-tricks",logs:"gratri-logs",goals:"gratri-goals",profile:"gratri-profile",offPlan:"gratri-offtraining-plan",offPreferences:"gratri-offtraining-preferences"} as const;
type DataKey=keyof typeof baseKeys;
interface PracticeLogRow {id:string;user_id:string;date:string;resort_name:string;trick_id:string;success_count:number;fail_count:number;memo:string;self_analysis:string;weak_point:string;next_task:string;snow_condition:PracticeLog["snowCondition"];video_urls:string[];}
interface GoalRow {id:string;user_id:string;season:string;type:Goal["type"];trick_id:string;target_rate:number|null;completed:boolean;}
interface ProfileRow {id:string;user_id:string;display_name:string;stance:Profile["stance"];trick_preferences:Record<string,Pick<Trick,"masteryStatus"|"favorite">>|null;}
const emptyProfile:Profile={displayName:"",stance:""};

const localKey=(key:DataKey,userId?:string)=>userId?`${baseKeys[key]}:${userId}`:baseKeys[key];
function readLocal<T>(key:DataKey,fallback:T,userId?:string):T{if(typeof window==="undefined")return fallback;try{const value=localStorage.getItem(localKey(key,userId));return value?JSON.parse(value) as T:fallback;}catch{return fallback;}}
function writeLocal<T>(key:DataKey,value:T,userId?:string,notify=true):void{if(typeof window==="undefined")return;localStorage.setItem(localKey(key,userId),JSON.stringify(value));if(notify)window.dispatchEvent(new Event("gratri-storage"));}
function reportFallback(operation:string,error:unknown):void{console.warn(`[Gratri Coach] Supabase ${operation} failed. localStorage fallback is active.`,error);}
async function userIdOrNull():Promise<string|null>{if(!isSupabaseConfigured||!supabase)return null;try{return(await getCurrentUser())?.id??null;}catch(error){reportFallback("auth",error);return null;}}
const trickPreferences=(tricks:Trick[])=>Object.fromEntries(tricks.map(({id,masteryStatus,favorite})=>[id,{masteryStatus,favorite}]));
const toLogRow=(log:PracticeLog,userId:string):PracticeLogRow=>({id:log.id,user_id:userId,date:log.date,resort_name:log.resortName,trick_id:log.trickId,success_count:log.successCount,fail_count:log.failCount,memo:log.memo,self_analysis:log.selfAnalysis,weak_point:log.weakPoint,next_task:log.nextTask,snow_condition:log.snowCondition,video_urls:log.videoUrls});
const fromLogRow=(row:PracticeLogRow):PracticeLog=>({id:row.id,date:row.date,resortName:row.resort_name,trickId:row.trick_id,successCount:row.success_count,failCount:row.fail_count,memo:row.memo,selfAnalysis:row.self_analysis,weakPoint:row.weak_point,nextTask:row.next_task,snowCondition:row.snow_condition,videoUrls:row.video_urls??[]});
const toGoalRow=(goal:Goal,userId:string):GoalRow=>({id:goal.id,user_id:userId,season:goal.season,type:goal.type,trick_id:goal.trickId,target_rate:goal.targetRate??null,completed:goal.completed});
const fromGoalRow=(row:GoalRow):Goal=>({id:row.id,season:row.season,type:row.type,trickId:row.trick_id,...(row.target_rate===null?{}:{targetRate:row.target_rate}),completed:row.completed});
const weekOrder:Weekday[]=["月","火","水","木","金","土","日"];
const legacyDays:Record<number,Weekday[]>={1:["土"],2:["火","土"],3:["月","水","土"],4:["月","火","木","土"]};
const record=(value:unknown):value is Record<string,unknown>=>typeof value==="object"&&value!==null;
function normalizeWeeklyPlan(value:unknown,weeklyDays:number,sessionMinutes:number):WeeklyOffTrainingDay[]{
  if(Array.isArray(value)&&value.every((item)=>record(item)&&typeof item.day==="string"&&Array.isArray(item.items)))return value as WeeklyOffTrainingDay[];
  const oldDays=Array.isArray(value)?value:[];const active=legacyDays[Math.min(weeklyDays,4)]??legacyDays[4];
  return weekOrder.map((day)=>{const index=active.indexOf(day);if(index<0)return {day,title:"休養日",focus:[],estimatedMinutes:0,items:[]};const old=record(oldDays[index])?oldDays[index]:{};const exercises=Array.isArray(old.exercises)?old.exercises:[];const items:OffTrainingPlanItem[]=exercises.filter(record).map((item)=>({name:String(item.name??"オフトレ"),category:item.category==="シバカツ"||item.category==="柔軟"?item.category:"筋トレ",amount:String(item.prescription??"自分のペースで"),purpose:String(item.ability??"基礎能力を高める"),caution:String(item.caution??"痛みが出たら中止する")}));return {day,title:String(old.theme??"オフトレDay"),focus:[],estimatedMinutes:items.length?sessionMinutes:0,items};});
}
function normalizeStoredPlan(value:unknown):OffTrainingPlan|null{if(!record(value))return null;const weeklyDays=Number(value.weeklyDays??0),sessionMinutes=Number(value.sessionMinutes??0);if(!weeklyDays||!sessionMinutes)return null;return {id:String(value.id??"cached-off-plan"),title:String(value.title??"オフトレプラン"),description:String(value.description??""),weeklyDays,sessionMinutes,weeklyPlan:normalizeWeeklyPlan(value.weeklyPlan??value.days,weeklyDays,sessionMinutes)};}

async function replacePracticeLogs(rows:PracticeLogRow[],userId:string):Promise<void>{if(!supabase)throw new Error("Supabase is not configured");const {error:deleteError}=await supabase.from("practice_logs").delete().eq("user_id",userId);if(deleteError)throw deleteError;if(rows.length){const {error}=await supabase.from("practice_logs").insert(rows);if(error)throw error;}}
async function replaceGoals(rows:GoalRow[],userId:string):Promise<void>{if(!supabase)throw new Error("Supabase is not configured");const {error:deleteError}=await supabase.from("goals").delete().eq("user_id",userId);if(deleteError)throw deleteError;if(rows.length){const {error}=await supabase.from("goals").insert(rows);if(error)throw error;}}

export const dataRepository={
  async getTricks():Promise<Trick[]>{const userId=await userIdOrNull();const fallback=readLocal("tricks",initialTricks,userId??undefined);if(!userId||!supabase)return fallback;try{const {data,error}=await supabase.from("profiles").select("trick_preferences").eq("user_id",userId).maybeSingle();if(error)throw error;const preferences=(data?.trick_preferences??{}) as ProfileRow["trick_preferences"];const tricks=initialTricks.map((trick)=>({...trick,...preferences?.[trick.id]}));writeLocal("tricks",tricks,userId,false);return tricks;}catch(error){reportFallback("getTricks",error);return fallback;}},
  async saveTricks(tricks:Trick[]):Promise<void>{const userId=await userIdOrNull();writeLocal("tricks",tricks,userId??undefined);if(!userId||!supabase)return;try{const profile=readLocal("profile",initialProfile,userId);const {error}=await supabase.from("profiles").upsert({id:userId,user_id:userId,display_name:profile.displayName,stance:profile.stance,trick_preferences:trickPreferences(tricks)},{onConflict:"user_id"});if(error)throw error;}catch(error){reportFallback("saveTricks",error);}},
  async getLogs():Promise<PracticeLog[]>{const userId=await userIdOrNull();const fallback=readLocal("logs",initialPracticeLogs,userId??undefined);if(!userId||!supabase)return fallback;try{const {data,error}=await supabase.from("practice_logs").select("*").eq("user_id",userId).order("date",{ascending:false});if(error)throw error;const logs=(data as PracticeLogRow[]).map(fromLogRow);writeLocal("logs",logs,userId,false);return logs;}catch(error){reportFallback("getLogs",error);return fallback;}},
  async saveLogs(logs:PracticeLog[]):Promise<void>{const userId=await userIdOrNull();writeLocal("logs",logs,userId??undefined);if(!userId)return;try{await replacePracticeLogs(logs.map((log)=>toLogRow(log,userId)),userId);}catch(error){reportFallback("saveLogs",error);}},
  async getGoals():Promise<Goal[]>{const userId=await userIdOrNull();const fallback=readLocal("goals",initialGoals,userId??undefined);if(!userId||!supabase)return fallback;try{const {data,error}=await supabase.from("goals").select("*").eq("user_id",userId).order("created_at",{ascending:true});if(error)throw error;const goals=(data as GoalRow[]).map(fromGoalRow);writeLocal("goals",goals,userId,false);return goals;}catch(error){reportFallback("getGoals",error);return fallback;}},
  async saveGoals(goals:Goal[]):Promise<void>{const userId=await userIdOrNull();writeLocal("goals",goals,userId??undefined);if(!userId)return;try{await replaceGoals(goals.map((goal)=>toGoalRow(goal,userId)),userId);}catch(error){reportFallback("saveGoals",error);}},
  async getOffTrainingPlan():Promise<OffTrainingPlan|null>{const userId=await userIdOrNull();if(!userId||!supabase)return null;const fallback=normalizeStoredPlan(readLocal<unknown>("offPlan",null,userId));try{const {data,error}=await supabase.from("offtraining_plans").select("id,title,description,weekly_days,session_minutes,plan_json").eq("user_id",userId).maybeSingle();if(error)throw error;if(!data)return null;const plan:OffTrainingPlan={id:data.id,title:data.title,description:data.description,weeklyDays:data.weekly_days,sessionMinutes:data.session_minutes,weeklyPlan:normalizeWeeklyPlan(data.plan_json,data.weekly_days,data.session_minutes)};writeLocal("offPlan",plan,userId,false);return plan;}catch(error){reportFallback("getOffTrainingPlan",error);return fallback;}},
  async saveOffTrainingPlan(preferences:OffTrainingPreferences,plan:OffTrainingPlan):Promise<void>{const userId=await userIdOrNull();if(!userId||!supabase)return;writeLocal("offPreferences",preferences,userId);writeLocal("offPlan",plan,userId);try{const {error:preferencesError}=await supabase.from("offtraining_preferences").upsert({id:`off-preferences-${userId}`,user_id:userId,equipment:preferences.equipment,weekly_days:preferences.weeklyDays,session_minutes:preferences.sessionMinutes,location:preferences.location,gym_available:preferences.gymAvailable,focus_ability:preferences.focusAbility,target_trick_type:preferences.targetTrickType,exercise_habit:preferences.exerciseHabit,injury_concern:preferences.injuryConcern,intensity:preferences.intensity,updated_at:new Date().toISOString()},{onConflict:"user_id"});if(preferencesError)throw preferencesError;const {error:planError}=await supabase.from("offtraining_plans").upsert({id:plan.id,user_id:userId,title:plan.title,description:plan.description,weekly_days:plan.weeklyDays,session_minutes:plan.sessionMinutes,plan_json:plan.weeklyPlan,updated_at:new Date().toISOString()},{onConflict:"user_id"});if(planError)throw planError;}catch(error){reportFallback("saveOffTrainingPlan",error);}},
  async getProfile():Promise<Profile>{const userId=await userIdOrNull();if(!userId||!supabase)return readLocal("profile",initialProfile);const fallback=readLocal("profile",emptyProfile,userId);try{const {data,error}=await supabase.from("profiles").select("display_name,stance").eq("user_id",userId).maybeSingle();if(error)throw error;if(!data)return emptyProfile;const profile={displayName:data.display_name,stance:data.stance} as Profile;writeLocal("profile",profile,userId,false);return profile;}catch(error){reportFallback("getProfile",error);return fallback;}},
  async saveProfile(profile:Profile):Promise<void>{if(!profile.displayName.trim()||!profile.stance)return;const userId=await userIdOrNull();writeLocal("profile",profile,userId??undefined);if(!userId||!supabase)return;try{const tricks=readLocal("tricks",initialTricks,userId);const {error}=await supabase.from("profiles").upsert({id:userId,user_id:userId,display_name:profile.displayName.trim(),stance:profile.stance,trick_preferences:trickPreferences(tricks)},{onConflict:"user_id"});if(error)throw error;}catch(error){reportFallback("saveProfile",error);}}
};
